name: Update blog posts
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: khaosdoctor/blog-post-workflow@1.7.3
        with:
          comment_tag_name: "DEVTO"
          feed_list: "https://dev.to/feed/slangedev"
      #- uses: gautamkrishnar/blog-post-workflow@1.7.3
        #with:
          #comment_tag_name: "MEDIUM"
          #feed_list: "https://medium.com/feed/@slange-dev"
      - uses: gautamkrishnar/blog-post-workflow@1.7.3
        with:
          comment_tag_name: "STACKOVERFLOW"
          feed_list: "https://stackoverflow.com/feeds/user/15338883"
