---
name: Building

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
            # Runs at every sunday 14:10
    - cron: "10 2 * * 0"

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: chk
      - uses: actions/checkout@v2


  fix:
    runs-on: ubuntu-latest
      - name: Misspell Fixing
        id: msf
      - uses: sobolevn/misspell-fixer-action@master


  createPullRequest:
    runs-on: ubuntu-latest
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Fixes by misspell-fixer"
          title: "Typos fix by misspell-fixer"
          body: ${{ steps.vars.outputs.pr_body }}
