name: misspell

on:
  create:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: slange-dev/slange-dev
        
    - uses: sobolevn/misspell-fixer-action@0.1.0
    - uses: peter-evans/create-pull-request@v3.8.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Fixes by misspell-fixer'
        title: 'Typos fix by misspell-fixer'
